-- User activation state for registration flows.
CREATE TYPE "UserStatus" AS ENUM ('PENDING', 'ACTIVE');

ALTER TABLE "User" ADD COLUMN "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE';

-- Lab membership independent from lab-scoped role assignments.
CREATE TABLE "UserLaboratoryMembership" (
    "userId" TEXT NOT NULL,
    "laboratoryId" TEXT NOT NULL,

    CONSTRAINT "UserLaboratoryMembership_pkey" PRIMARY KEY ("userId", "laboratoryId")
);

ALTER TABLE "UserLaboratoryMembership" ADD CONSTRAINT "UserLaboratoryMembership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "UserLaboratoryMembership" ADD CONSTRAINT "UserLaboratoryMembership_laboratoryId_fkey" FOREIGN KEY ("laboratoryId") REFERENCES "Laboratory"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Invitation codes generated by lab managers before user self-registration.
CREATE TYPE "UserRegistrationInvitationStatus" AS ENUM ('OPEN', 'CLAIMED', 'APPROVED');

CREATE TABLE "UserRegistrationInvitation" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "laboratoryId" TEXT NOT NULL,
    "status" "UserRegistrationInvitationStatus" NOT NULL DEFAULT 'OPEN',
    "createdBySubject" TEXT,
    "createdByClientId" TEXT,
    "registeredUserId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "registeredAt" TIMESTAMP(3),
    "approvedAt" TIMESTAMP(3),

    CONSTRAINT "UserRegistrationInvitation_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "UserRegistrationInvitation_code_key" ON "UserRegistrationInvitation"("code");

CREATE UNIQUE INDEX "UserRegistrationInvitation_registeredUserId_key" ON "UserRegistrationInvitation"("registeredUserId");

CREATE INDEX "UserRegistrationInvitation_laboratoryId_status_idx" ON "UserRegistrationInvitation"("laboratoryId", "status");

ALTER TABLE "UserRegistrationInvitation" ADD CONSTRAINT "UserRegistrationInvitation_laboratoryId_fkey" FOREIGN KEY ("laboratoryId") REFERENCES "Laboratory"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "UserRegistrationInvitation" ADD CONSTRAINT "UserRegistrationInvitation_registeredUserId_fkey" FOREIGN KEY ("registeredUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
