import { randomBytes } from 'node:crypto';
import { readFileSync } from 'node:fs';

const preferredOrder = [
  'DATABASE_HOST',
  'DATABASE_PORT',
  'DATABASE_USER',
  'DATABASE_PASSWORD',
  'DATABASE_NAME',
  'DATABASE_URL',
  'HYDRA_ADMIN_URL',
  'PORT',
  'SEED_ADMIN_EMAIL',
  'SEED_ADMIN_NAME',
  'SEED_ADMIN_PASSWORD',
  'SEED_USER_EMAIL',
  'SEED_USER_NAME',
  'SEED_USER_PASSWORD',
];

function parseScalar(value) {
  const trimmed = value.trim();
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }

  return trimmed;
}

function parseRuntimeEnv(source) {
  const values = {};
  const generated = {};
  let inRuntimeEnv = false;
  let section = null;
  let currentValue = null;
  let currentGenerated = null;

  for (const rawLine of source.split('\n')) {
    const line = rawLine.replace(/\s+$/, '');
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    if (/^\S/.test(line)) {
      inRuntimeEnv = trimmed === 'runtime_env:';
      section = null;
      currentValue = null;
      currentGenerated = null;
      continue;
    }

    if (!inRuntimeEnv) {
      continue;
    }

    if (line === '  values:') {
      section = 'values';
      currentValue = null;
      currentGenerated = null;
      continue;
    }

    if (line === '  generated:') {
      section = 'generated';
      currentValue = null;
      currentGenerated = null;
      continue;
    }

    if (section === 'values') {
      const valueMatch = line.match(/^    ([A-Z0-9_]+):(?:\s*(.*))?$/);
      if (valueMatch) {
        const [, key, rawValue = ''] = valueMatch;
        if (rawValue.trim()) {
          values[key] = parseScalar(rawValue);
          currentValue = null;
        } else {
          currentValue = key;
        }
        continue;
      }

      const templateMatch = line.match(/^      template:\s*(.*)$/);
      if (currentValue && templateMatch) {
        values[currentValue] = { template: parseScalar(templateMatch[1]) };
        currentValue = null;
      }
      continue;
    }

    if (section === 'generated') {
      const generatedMatch = line.match(/^    ([A-Z0-9_]+):\s*$/);
      if (generatedMatch) {
        currentGenerated = generatedMatch[1];
        generated[currentGenerated] = {};
        continue;
      }

      const generatedPropertyMatch = line.match(/^      ([a-z_]+):\s*(.*)$/);
      if (currentGenerated && generatedPropertyMatch) {
        const [, key, rawValue] = generatedPropertyMatch;
        generated[currentGenerated][key] = parseScalar(rawValue);
      }
    }
  }

  return { values, generated };
}

function resolveTemplate(template, env) {
  const rendered = template.replace(/\$\{([A-Z0-9_]+)\}/g, (_match, key) => {
    if (env[key] === undefined) {
      throw new Error(`Missing template value: ${key}`);
    }

    return env[key];
  });

  if (rendered.includes('${')) {
    throw new Error(`Could not resolve template: ${template}`);
  }

  return rendered;
}

function quote(value) {
  return `"${String(value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$')
    .replace(/`/g, '\\`')}"`;
}

const source = readFileSync('idp-client.yaml', 'utf8');
const { values, generated } = parseRuntimeEnv(source);
const env = {};

for (const [key, spec] of Object.entries(generated)) {
  if (spec.type !== 'hex') {
    throw new Error(`Unsupported generated value for ${key}.`);
  }

  env[key] = randomBytes(Number(spec.bytes ?? 32)).toString('hex');
}

const templates = {};
for (const [key, value] of Object.entries(values)) {
  if (value && typeof value === 'object' && value.template) {
    templates[key] = value.template;
  } else {
    env[key] = String(value);
  }
}

for (const [key, template] of Object.entries(templates)) {
  env[key] = resolveTemplate(template, env);
}

const keys = [
  ...preferredOrder.filter((key) => key in env),
  ...Object.keys(env)
    .filter((key) => !preferredOrder.includes(key))
    .sort(),
];

const lines = [
  '# Generated by ./init.sh from idp-client.yaml.',
  '# This file is ignored by Git. Keep local credentials here only.',
  '',
];

for (const key of keys) {
  lines.push(`${key}=${quote(env[key])}`);
}

process.stdout.write(`${lines.join('\n')}\n`);
